package easy;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class DIStringMatch {
    public static void main(String[] args) {
        System.out.println(Arrays.toString(new DIStringMatch().diStringMatch("IDIIIIIIDDIDDIDIIIDDDIDIDDDIIDIDIIIIDDDIIIDIIDIDIIIIIIDDDIIIIIIIIIDDDIIIIDDIDDIDIDIDDDIIIDIIIIDDIIIIIIDIDDDDIDIIIIDDDDIIIDIIDIDDDIDIIDIIDDDIDIDDIDDIDIDIIIIIIDIIDIDDDDDIDIDDDIDIIIIIIIIIIIDIIDDIDIIDIDIDIIIDIDDIIIDDIDIDIIIDIIIIIIIDDIIDDDIDDDDDIIDIDDDIIDDDDDIDIDIIDIDDIIDDDDIDDDIDDIIDDIDDIDDDDDDIDIIIDIDDIIDDDIIDIDIDIDIIDIIIDDDIDIIDIDIIDIIDIDDIIIDDIIDIIDIDIIDDIDIDDDIDIIDDDIDIDDDIIIDDDIDDDDIIDIDIIIDIIDIIIDDDDIDIDDDIIIIIDDDIDIDIIIDIIDIIIDIIIIIDDDIDDDIIDDIIDIIDDDIDIDDDDDIIIIIIIIIIDIIDDIIIDDDIIIDIDDIDIIDIDDDDIIDDDDDIDDIDIDIDDDDIDIDDIDIDIIIDIDIIDIDDDDDIIDDDDIIIIIDIIIIDIIDDDIIIDDIDIDDIDIIIDDDIDIIIIIIDDDDDDIDIIDIDDDDIIIDDIIIDDDDDDDDDIIIDDIIIDIIDDDIDIDIIDIIDDDDIDIDIDDIIIIIDDDDDDIDDIIIIDIDDDIDIDDDDDDIIDIIDIDIIDIIDDIDDDDDDIDDIIDIIDDDIIDIIDDDDDDIDDDDIDIDDDDIIIIIDIDDIIDDIDIIDIIIDIDDDIDIIIIIDDDDIIDDDIIDDIIIDDDIIDDIDDIIDDIIDIDDIIDIIDDDDDIDIIDDDDDDIDDIIDIIIDDIDIIIDDIDIDDIDIDIDDIDDIIIDIDDIIIDDIDDDIIDDDIDIDDIDIDDDDDDIIDIDDIIDDDDIIIIIDIDIDDDIIDIIIIDDDIIIIDDDIIIIDIDIDIIIIDDDIDDDDDIDDIDDIIDIIDIDIDIDDDDDIDIIIIIDIDDDIIIDDDDIDIDIDDDDIDDIIIIIDDIIDDIIIIDIIDDIDDIDDIDIIDDIDIIIDDIDIDDIDDDIDDIIDDDDIIDIIDIDIIDDIDDIIIDIDDDDDDDIIIDDIDIDIIIDIIDIDDDIDIIDDDIDIDIDIIIIDIDIIDIDIIIIDIDDIDIDIIDDDIIIIDDIDDIDDDDIIIDIIDDIIIIDIDIDIIDIIIIDDDIDDIIDIDIDDIIIDIIIIDDDIIDIIDDDDIDDIIIIIIIIIDDIIIDDIIDIDIIDIIIDIIIIIIDIIDDDDDIDDIDIDIIDDDIDDDIIIDDDIIIDDDDIDDIIDIDIDDDIDIIIIDIDIIIDIDDIDDDIIIDDDDIIIIDIDIIDDDDDDDIIDDDIDDDDIIIIIDDIDIDDIDDDIIIIIDDIIIDIIDIDDDDIDDIDIDIIDIDDIDIIDDDDIDIIDIIIDIDDDIIIIIDIIDDIDDIIIIDIIDDIIDIDDDDIDIIDIDIDIDIIDDIIIDIDIDIIDIIDDDIIDIDDDIIDIIDDIDIDDIIDIDIDIDDDDDIIDDIDIIIDIDDDDDIDIDDIDDDDIIDDIIIDIIDIIDDDIIIIDDDDIIDDDIIDIDIDDDDDDIDDIIIDDIDIDIDIIDDDIIDIIDDDDIIDDIDDDDDDIDDIDIDDDDIIDIDIDDDIIDIDIIIDDDDDIIIIDIDIIDIDIDDIDDIIIIIIDIIDIIDDIIDDDIIIDIDIIDDDIDIIIDDDDDIIIDDIIDIDIDDIDIIIDDIIIDIDDIIIIDDIIIDDIIDIIIIDIIIIIDIDIIDIDIDDIIDDIIIIIDIIIIDIDIDDIIDIIIIDDDIDDIIIDDDDDDIIIIDIIIDDIIDIIIIDIIDDIDIIIDDIDIDIDDDDIDIDIDIIIIDDDDIDIIDDDIIDDIIDDIIIDDDDDDIDIIDDDDIDIDDDDDDIDIDIIIDDIDDIDIIDIDDDDIIIDIIDIIIDIDDIDIIDIDIDIIIDIDDIIIDIIDDIIIDIDDIIIDIDIIDIIDIIIDDIIDIDDIDDDDDIIIDDDIIDIIDIDDDIIIIDDIDIDIIIIIIDIDDIDDIIIDDIDDDDDDIIIDDIDIDIIIIIIIDDIIIIIDDDIDDDDDDDIIIIDIIDDIIIIDIDIIDDDDDDIDIDDDDDIIDIDDDIIDIDDDDIDDIDIIDIIDDDDIIIDIIDDIDDDIIIIDIIIDIDIIIDIDDIIIIDIDDDIDDIIDDIDIDDIIIIIDDIDDDDDIDIIDIDIDIIIDDIIDIDIIIIIDIIDIIDDIDDDDIDIIIDDDDDDIIIDIDIDDDIIDDDIDIIIDDIDIDDDDDDIIDDDDDIIDIDDIDIIDDIDIDIIDDDDDDIDIDIIIIIIIIIDDDIIIIDIIDIDIDDIIIIIDIIIIIDDDDDIDDDDDDIDIIDDIIIIIIDIDIDDDIDDDIIIDDIDIIDDIIIDDDDIIDIIIIDIDDDDDDIIIIIIDIDDIIIDDDDIIDIIDDDIIDDDIIDDDIIDDDDIDIIDDDIIIDDDDDDDDIIIDDIDDIIIIIDIDDDDDIIIDIDIIIIDDDDIIDIDDDDDDDDDDIDDDIDIDDDDDDDIIDDIIIIDIIIDIDIDDIDDDDIDDIDDDIIDDIDIIIDDIDIIIIIDIDIIDDDDDDDIDIIIDDDIDDIDIDIIDDIDDDDIDDDDDDDIIIIDIIIDIDIDDIDDIDIDIDIIIIDIDDDIDDDIDIIIIDIDIIIIIIDIIDIDDIDDDIDIIIIDIIDDDDDIIDIIIDIDDDDIIIIIDDDIIIIIIDDIDIIIIDDIIIDIDIIIIDIDIDDDIIIIDDIDIDIDDIDDDIIIDDDIDIIDIDDDIIDIIDDIDDDDIDDIIDDDIIIIIIIIIIIDIDDDDIDDDDIDDDDIDIDIIIDDDIIDDIDIIDIIDIDIDIIIDIDIDDDIIDDIIIDDIIIDDIDIIDDIIIIIIIDDDDIDIIIIDDDIIIIDIDIDDDDIIDDDIDDIIDIIDDDDIDDIIDIDIDDIDIIIIDIIIIDDDIDIDDDDDIDIIIIDDIDDIIDDDDIDDIIIDDDIDIIIDIDIDDIDDDDDDIDDDIDDIDDIIDIDDDDDIDDDIDIIIIDDDIDIDDIIDIIIDDIDDDIIDIIDDIIDIDDDIDDDIIDDIIDIDIIIIDDIIDDIIIIIDDDIIDDIDIIIIDDIIIIIIDIIDIDIIDDIIDDIIIIDDIIDIIIIDDIIIIDIDDDDIIIDDIIIIIDIDIIDIIIDIIIDIIDDIDDDDDIDDDDIIDIDIIDIDIIDIDDIDDDDIIIIDDDIIIDIDIIIDIIIIDDDIIDIIDIDDDIDIIIIIDIDDIDIIDDIIDIDIIIIDDIDDDDDIIDDIDIDDIDDIIDIIDIDIDIIIDDDDIIIIIIDDDIDDDDDIDIDDIIDDDDIIIDDIIIDDDDIDDDIIDIDDIIIIDDIIIIIDIIIIIIDDIIIIDIDDIIIDDDDIDIIDDDIIDDIDDDIDIIIIIIIIIDIDIDDDDIIIIIDIDDDIIIDDIDDIDIIDDDIIIDIIDDIIIDIDIIIIDIDDDDIIDIIIDIIIIDIIDDDIDIIDIDDDIDIDDIDIIIIIIIIIDIDIIDIIDIIIDIDDDDIIIIDDIDIDIIIIIDIIIIIDIIIIIIDIIDDDIIIIDDIDDDDIDIDDDIDDIIDIDIDDIDIIIIDDDIIDDDIDDDIIIDIIDDDDIDDDDDIDIDDDIIIDIIIDDIIDIIDIIDDIDDDDIDIDIIIIIIIDIDDIDDDIDDDDDDDDDIIIDIDDDDDDIIIDIDIIIDDIIDIIIDIIIIIDIDDDDIIDIIIIIDDDDIDIDDDDIDDDDIIDIDIIIIDIIIDIIDIDDIIDIDIIDIDDDIDIIIIDDIIDDDIIIIDIIIDDDDDDIIIIIDDIIDDDIDDIIIIDIIDIIIIDIIDDDIIIDIIIIDIDDDIDDIIIIIIIIDDIIDIDIDIIIDIIIIDDDIDIIDIIDIDIIIDDDDIIIDDDIIDDDIIDIIIDDDIDDIDIIIIDIDIIDIDIIDDDDDIIDDIIIIDIIDIIDDIIIDDDIIIDDIDDDDIDIIDIIIIIIIDIDIDDIDDDDDIDIDIIIDDDDIDIDDIDIIDIIDIIDDDIDDDDDIDDIIIIDIIIDDDDIIIDIIDDDDDIDDDDDDIDDDIIDDIIIIIDIDDIDIIIDDIIIIIIDDDDIIIDDDDIDDDIDDIIDDDIDDDDDDIIIDIDIIDIDDIIDIDDDIIIIIIDDDDDIDDDDDDDIIDIIIDIIIIDDIIIDDDIDDIIIIDIDIIIDDDIDIDDIIDDDDDDDIDDIIDDIDDDIIDDIIIIDIDDIIDIIDDIIDIIDIDDIIIIIIIDDIIIIDIIDIDIDIIDIIDDIIIIIDIIIDDIIDDDIIDDDDIIDDDDIIDIDDIDDDIIDIIIDDDDDIIIIDIIIIDDIDDDIDDDDIIDDDDIDDDDIIIIDDIDIIDDDIDIDDIIDDIIDIDIDDDIDDDDDIDDDIIDDIDIDIDIDDDDDDIDDDIIDDIDIIDDDDDIIIIDIIIIIDDIDDIDDIDDDIIIDIIDDDIIIDIDIDDDDDIIIDIIDIIIDDIIDIDDDIIDIDDDIIIDIIIDIDDIIDDIDIIIIIDIDDIDDIDIDIIDDDDDDIDIIIDDIIDDIDIDIIDDIDIDIDDDDDIDDIIDIIDIIIIDDIDDIIIDDDIDDDDDIDIIIIDIDDDIDIIDDIIIIDIIIIDDIDIDDIIDDIIDIIDIDDDDDIDIIIDIDDIIDIDDDDIIIDIIIDDIIDIIDDDIDIDIIDIIDIIDIDIDIIIIIIDIDDIIIDDIDIDDIDDDDIDIDDIIIDIIIDIIDDIIIDDDIDDIIDIDDIDDDIDIIDIDIIDDDDDIDIIIIDIIIIIDDIDIDDDDDIIDDIDDIIDIIIDIDDDIDDDDDIDIIIIIDIDIDDIIDIDIDDIDIIDDDDIDDDIDIIIDDDDIIDIIIDIDIIDDDIDDIDDDIDIIIIDDIDDDIDDIDDIIIIDDDDIDDIDDDDDDDIDIIDDIDIIIDIDDIDDDDDDIDDIIIDDDDIIIIDIIIDIIIIIIIDIIDIIIDIIDIDIIIIDIDDDIIDIIIDIDDDIDIIIDIIIIDDDDDIDIIDIIDIIIDDDDDIDDDDDIDDIDDDDIIDIIIDDIDDIIDDIIDDDDDDDIDIDDDDIDIDDDDIIIDDDIIDDIDIIDIIDIDDDIIIIDIIDIDDDIDDIDDIDIIDDIDIDDIIIDIIDIIIDDDIDIIDIIIDDIDDDDIIDDIIDDDIDIDIIIDDDIIIIDDIIIIIDDDDIIIIIIIIDIDIDIDIIDIDIIDIIIIIIDIDDIDDIIIIDDDIIDDDDIIDIDDIDDIDDIDDDIDDIDIDDDIDDDIDIDDDDDIIDIIIDIDDIIDDIIIIIIIIDIIIIDDDDDDDIIIIDDIDIIDDDDIDIIDDIIIIDIDIDDIDIIDDIIIIIIIIDDIDIIDIIIDIIIDDDIIDDIDDIIDDIIIIDDIIIDDDDIDDDIDDDIIIDDDDIDDIDDDDIIIIDDIIDDIIIDIIIDIIDDIIDIIIDDIIIDIIIIIDIDIDIDDIDDIIDIIDDIDDIIDDIDIIIDIIDIIIIIDDIDDIIDIDDIIIDIDDIIDDIIDDDIIIIIDDIIDIIIIIDDIDDDIIDIDIIDIDIIDDDIIIIIDIDDIIDDDIDDDDDIIIDDIIDIDDDDIIIDIDIIIIDDDIIDIDIDIDIDIDDDDIDIDIDIIDIIIDDIDIIIIIIDDIIDDIIDIIIIDDIDIIIDDIIIDIDDIDIIIDDDDDIDIIIDDDDIIIIDIDIDDDIDIIIDIDIIIIIIDIIIIDIIDDDIDDDDDDDIDDDDDDDDDDIDIIDDDDIDDDIDIIIIDIDIIIIIDDDIDDDIIDDIIIIIIIIDDIIDDDDIDIDIIDIDDIIDIIDIDIIDIDDIIIDDDIDIIIIDIDIIDDDIIIDIIDDIIIDDDDIIDIDDDDIDDDIIIDDIDIDIDDDDIIDIIDDIDIIIDIIIIIDDIIIDIDIDIIIDDDDIDIIDIDIDDIIIDDIDDIDDDIDIDDDDDDDDDDDDDIIDDDIDDDIIDDIDDDDDIIDDIDDDIIDDDIDIIDIIIDIDIDIIDDIDIIIIDIDIIDIIIDDDDIDDIDIIDIIDDIIDDDDDDIIIDDIIIIIIIDIDDDIDIIIDIIIDIIDIDDDDIDDDIDDIDIIDDDIDDIIIDIIDIDDDDDDDIIIIDDIDIDIIDDIIDIDIIDIIDDDIIDDDDDDIIDIIDIDDIIIDDDDDDDDIIDIIDIDDDDIIIIIIDDIIDDIDIDDIDIIIDDIDDDIDDIDIIIIIIIDDDDDIDIIIIIDIDDDIIDDDDDDDIIDIIIDDIIDDIIIIDIDIDIIDDIDIIDIIIIDDDDDIIIIIIIDDIIDDIDDIIIDDDDDDDDDIIDIIIDDIDIDDDIDIIIIIDDDIIIIIDIIDDIIIDIDDIDIDIIIIIIIIDDDIIDIDDIDDIDIIIDDIIDDIIIIDDDDDDIDDDDDDIDDDDIDIIIDIIIIDDDIIDDDIDDDDDIDIIIIDIDDDIDDDIIIDIIIIIIIIIDDIIDDDIDDDIDDIDIDIIDDDIIIDIIDDDDIDIDIDDDDDDDDDDDDDDIIIDDIIIDIIIDIDDIDDIDDDDIDDIDDDIIDDDDIIDIIDDIDIIIIIDDIDIDIDDIDDIIIIDIDIIIIIDDDIDIDIIIDDIDDIIDIIIIDDIDIIDDIIDIDIIIDIDIIIIDDDDIIIIDDIIIDIDIIDIIDIDIDIDIIIDDIDDDDIIDIIDDIIIDIDDDDIIDDDIDDIDIIDDIDDDIIIIDDDIDIDDDDIDIIIIDIDIIDDIIDDDDDDDIIDDDDIDIIIDIDDDIDDIIDIIIIIIIDIDIDDIIIIDIIIDDIDIDDDDIIDIIIDIDDIIDIIDIDIDDDDDDIDDDIIDIIDIDIIIDDDIIDDDDIIIDIDIIIIDDIIIDIDIIDDDIDIDIDDIIDIIDDIDDIDDIDDIDIIIDDIIDDIIDDIDIIDIDIIIDDDDIIIIDDIIIDDDIIIIDIIIDIDIIIIDDIIDDIIIIDIDIIDIDDIIIDIDDIIIDIDDDIDIDIDIDIDIDDIIIIDIDDIDIDIDDDDIIDIIIIDDDIDDDIDIDIDIIIDDIDDDDDDIDIDDIDIIDIIDIIIDIDIDIDIIIIIIDDDDIDDIIDIDIDDIIDIDDDIIIIDIDDDDIDIDIIDDDDDDIDIDIDDDDDDIIIDDIDDIIDDIIDIIIDDIIDIDIDDIIDIIDIIIIIIDDDDDDIIDDIIDDDIDIIDDDIIIIDDDIIIIIDDDIDIIDDIDDIIDDDDDIDIDDIDIDDDDDDIDDIIDIIDDDDIIIDDIIIIDDDIIIDDDIIIIIDIDDIIIDDDIDIIIDDDDDDIDDIIIDIDIIDIIDDIDDDDDDIDDIDDIIIDIDDIIDDIDDDIIDDDIIIIDDDDIIDIIDDIIIIIIDDIDIIIDIIDDIDDIIIDIIDDDIIDIDIIDDDDIIDDDDDIDIIIDDDIIIIIIDIDDDDIDIIIDIDIDDDDDDIIDDDDDIDDIIIIDDIDDIIIIDDDDDDDIIIDIIDIIDDIDDIIIIIIIIIIDDIIDIIIIDIIIDDIIIIIIIIIDDIDIIDIDDDDIIDIDDIIDIDIIDDIIIDIDIIIIIIDDIDIIIDDIDDDIIDIIDDDDIDIIIDIDDIDDDIDIIDDIDDDDIDIDIDIDIIDIDIDDIDDIIDIDDIDIIDIDDIIIDIDIIDDIIDIDIIDIDDIDIIDDDDDIDDDDDIIDDIIIIIIDIIDDDDDIDIDIDDDIIIIDIIDDIDDIDIIIIIIIDIDIIIIDIIIIDIIDIDIIDDIDDDIIDIDIDIDDIIIDDIIDDIIDDDDIDDDIDDIIDIIIDIDIDDDIIDIIIDIDDDIIDDIIIIIIIIIDIDDIIIDIDDDIDIDIDDDDDDIDDDDDIDIDIDDIDIDIIDDIIIIDDIDDDIIDIDDIDDDIIDDIDIDDIIDIDIIDIIIIDDIDIIDIDDDDIDIIIIDIIIDIDIDDDDDDIIIDIDDIDIDDIIDIIDDDIDDIDDDIDIDIDIIIDIDDDIDDDDDIDDIDDDDIDIIDIDIIDIIDDDDIDIDDIDIIDDDDDDIIIIIDIIDIDDIIDIDDIIIDIDDIIDIDDDIDIIDIIDIDIDDDIDIIIIDIDDIIIDDDDIIDIDIDDDDIIDDDIDDIDDIIDIDDDDIDIIDIIDDIIDIDIDDIDIIDDIDIIIIIDDIIDIIDDIIIDDDDIIIIIIIIIIDIIDIDDIDDDIDDDDIIIDIDIDIIIIIIDIIDDDIIDIDIIDIDIIIIIIDDIDIIDIDDIIDDIDIDIDDDDIIDDIIDIIDDIIIDIDDIIDDIIDIIIIIDIIDIIIDDDDDDIDDIIIIIDDDDIDIIDDDIIDDIDIDDDDDDIDDDIIDDIIIDIIIDDIDIIDDDIIIIIIIIIDDIDDIDDDDIIDDDDDIIDIIDIIIDIIIIIDIIDDIIDDDIIDIIDIDIIDDDDIDDIDIDDIDDIDIDIIDIDIIDDIIDIDDIIDDDIIIDDIDDIIIIIDDDIDIDIDDIIDIIDIDIDIDIIDIDIDIDDIDDDDDDDIIDIDIDIDIIDDDDDIIDDDIIIIIIIIIDIDDDIDDIDIDIDIDIDIIDIIDDIIDIIDIDIDDIIIDDIDDDIDIIDDIDDIIDDIDDIDIDDIDDDDIIDIDIDIIDIIDIDIIIDDIDDIIIIDDIIIIDIDDDDIIIDDIDIIDIDIDIIIDIIDIIIIIDIDIIIDIIIDDDIDIIDDIDIIIIIIDIIIIDIDDIIIDDIIIIIIDDIIDIIIDIDIDDIDIDDDIDIDDIIIIDDDIIDDIIIDIDIDIIIDIIIDDDIIIIDIDIIIDDIIIDIDDDIDIDDIIIIDDIIIDDIDIIIDDIDDIIDDDDIDIIDIIDIDDIDDIIDDIIIIDDDIDIDDIDIDDDDDIDDIDIIDDDIIDIDDIDIDDDDIDIIIIIIDIIIDIDIIIIDIIIDIDIDDDDDIDIDDIDDDDIDDDDDDIDIIIIDIIIIIDIIDDIDDDIDDDDIIDDIIIDIDIDDDIIDDDDDDDDDDIIDIIDDIDDDDDDIIIDIIDDIIDIIIDIIDDDDDDIIIDDIIIDDIIDIDIDDDIDIIDDIIDIIDDDDIDDDIDDIIIIDDDIIIDIDDIIIDDIIIDIIDIDDIDIIDIIDIDDDDIDDDDIIDDIDDDDDDDIIDIIDDDIDIIIDDIIDIDDIIIIIDIDDIDIDDDDIIDDDIIIIDDIDIDDIIIDDIDDIDIIIDDIIDDIDIIIDDDIIDDDDIIIDDDDDIIDDIIDIDIIDDIDDDDDDIIIDDIIIIIDIDDDDIIIIIIIDIDDIIDIDDIIDIIDDDDIIIIDIDDIIIDDDIDIIDIDDDIIIDIIIIDDDDIDDDIDDDDDDIDIIDDIDDIIIDDDIIDIIDIDDIIIIDIDIIIIIIIIDDDIIDDIDIIIDDIDIDIDIIDIIIIDIDDIDIIIIDIIIDDDDIDIDIIDIIDIIIDIDIIIIDDIDIDIIDDDIIIDIIIDDDDIDIIIIDIDDDIDIDDDIIIDIIIIDDIDIIIIDDIIIIIDDIIDDDIDDIIDDDIDIDDDDIDDIIDDDDDIIDIDDDIDDIDIIDIDDDIDIDIDDIIIIDIIIIDIIDDIDDIIDIDDDDIDDDIDIDIIDIIDDIIDIDIDDIIDIDDDDDIIIIIDDDDDIIDDDIDIIIDDDDDIIIIIIDDDIIIIIIDDIIIIDIDIIDIDDIIDDDDDIIDIIIDDIIIDDIDDDDIDDDIIDDDIIIIDDIDDDDDIDDIDIIDDDDDDIIIDDIDIDIIIIDDIIIDIIDIDIIDDIIDIIIDDIIIIDIDIIIIIDDIIDIIIDIIDDDIIDDDDIIIDIIDDIIDDIDDIDDDDIIIDDDIDDIDDIIDDIIIIDIDIIDIIDIDDDDDIIDIDDDDDDIDDIIIIIIDIDIDDDDDDDIIDDIIIDIDDDIDDDDIDDIIIDDIDDDIIIDIIIDDDIDDDIDDIDDIDIDIIIIDDIDIID")));
    }
    public int[] diStringMatch(String s) {
        int n = s.length();
        int[] perm = new int[n+1];
        for (int i = 0; i < n + 1; i++) {
            perm[i] = -1;
        }

        Set<Integer> used = new HashSet<>();

        int i = 0;
        boolean update = false;
        while(i<n+1)
        {
            if(i == 0){
                perm[i]++;
                used.add(perm[i++]);
                update = false;
                continue;
            }

            switch (s.charAt(i-1)){
               case 'I' : {
                   int next = update ? getFirstBiggerThanMe(perm[i], n+1, used) : getFirstBiggerThanMe(perm[i-1], n+1, used);
                   if(next != -1){
                       perm[i] = next;
                       used.add(perm[i++]);
                       update = false;
                   } else
                   {
                       update = true;
                       used.remove(perm[--i]);
                   }
                   break;
               }
               case 'D' : {
                   int next = update ? getFirstSmallerThanMe(perm[i], used) : getFirstSmallerThanMe(perm[i-1], used);
                   if(next != -1 || (update && perm[i] > perm[i-1])){
                       perm[i] = next;
                       used.add(perm[i++]);
                       update = false;
                   } else
                   {
                       update = true;
                       used.remove(perm[--i]);
                   }

                   break;
               }
            }
        }

        return perm;
    }

    public int getFirstBiggerThanMe(int me, int n, Set<Integer> used){
        int i = me+1;
        while (i<n){
            if(!used.contains(i)){
               return i;
            }
            i++;
        }

        return -1;
    }

    public int getFirstSmallerThanMe(int me, Set<Integer> used){
        int i = me-1;
        while (i>=0){
            if(!used.contains(i))
            {
                return i;
            }
            i--;
        }

        return -1;
    }

}
